import { t } from '../i18n.js';

export const STORY_COUNTRY_IDS = ['UKR', 'POL', 'DEU', 'FRA', 'ESP', 'PRT', 'ITA', 'TUR', 'SWE', 'EGY', 'JPN', 'CHN'];

const STORIES = {
  UKR: {
    id: 'UKR',
    title: () => t('Село Сонячне'),
    npc: {
      id: 'ukr-medic',
      kind: 'medic',
      site: 'village',
      name: () => t('Медик Олена'),
      intro: () => t('Село тримається, але людям потрібен герой. Почни з порятунку біля хліва.'),
    },
    objectives: [
      {
        id: 'ukr-rescue',
        kind: 'rescue',
        icon: '🆘',
        site: 'barn',
        title: () => t('Врятуй людей із хліва'),
        start: () => t('Люди сховалися в хліві. Відкрий двері й виведи їх.'),
        done: () => t('Люди врятовані. Медик допоможе біля села.'),
        reward: 90,
        horde: 10,
      },
      {
        id: 'ukr-signal',
        kind: 'hold',
        icon: '📡',
        site: 'tower',
        title: () => t('Віднови сигнал села'),
        prompt: () => t('Тримай E — запусти сигнал'),
        start: () => t('Без сигналу інші рятівники не знайдуть село.'),
        done: () => t('Сигнал пішов! Тепер захисти площу.'),
        hold: 2.4,
        reward: 110,
        horde: 14,
      },
      {
        id: 'ukr-defense',
        kind: 'defense',
        icon: '🛡️',
        site: 'village',
        title: () => t('Оборони сільську площу'),
        start: () => t('Зомбі почули сигнал. Тримай площу до кінця атаки.'),
        done: () => t('Село в безпеці. Арена боса відкрита.'),
        seconds: 22,
        reward: 130,
        horde: 0,
      },
      {
        id: 'ukr-rebuild',
        kind: 'rebuild',
        icon: '🏗️',
        site: 'village',
        title: () => t('Знайди сокиру й кірку та віднови центр міста'),
        start: () => t('Знайди інструменти, добудь 120 дерева і 50 каменю, потім відновлюй центр 30 секунд.'),
        done: () => t('Центр міста відновлено! Шлях до боса відкрито.'),
        reward: 240,
        horde: 0,
      },
    ],
  },
  POL: {
    id: 'POL',
    title: () => t('Крижане депо'),
    npc: {
      id: 'pol-keeper',
      kind: 'granny',
      site: 'townSquare',
      name: () => t('Доглядачка депо'),
      intro: () => t('Місто замерзає, а поїзд стоїть. Запали вогнища й відкрий шлях до депо.'),
    },
    objectives: [
      {
        id: 'pol-bonfires',
        kind: 'activate',
        icon: '🔥',
        site: 'bonfires',
        title: () => t('Запали 3 вогнища'),
        prompt: () => t('Тримай E — запали вогнище'),
        start: () => t('Без тепла люди не дійдуть до евакуації.'),
        done: () => t('Вогнища горять. Тепер запускай поїзд.'),
        count: 3,
        hold: 1.8,
        reward: 110,
        horde: 10,
      },
      {
        id: 'pol-train',
        kind: 'hold',
        icon: '🚂',
        site: 'railDepot',
        title: () => t('Запусти рятувальний поїзд'),
        prompt: () => t('Тримай E — заведи поїзд'),
        start: () => t('Депо поруч. Якщо поїзд рушить, люди матимуть шанс.'),
        done: () => t('Поїзд готовий. Але біля замку засідка.'),
        hold: 2.8,
        reward: 130,
        horde: 16,
      },
      {
        id: 'pol-castle',
        kind: 'castle',
        icon: '🏰',
        site: 'castleRuin',
        title: () => t('Штурм великого замку'),
        start: () => t('Знайди вибухівку, підірви ворота, зачисть замок і врятуй полонених.'),
        done: () => t('Полонені врятовані. Бос чекає на окремій арені.'),
        count: 30,
        reward: 250,
        horde: 0,
      },
    ],
  },
  DEU: {
    id: 'DEU',
    title: () => t('Осінній конвой'),
    npc: {
      id: 'deu-greta',
      kind: 'granny',
      site: 'cityGate',
      name: () => t('Пекарка Грета'),
      intro: () => t('Залізний Барон перекрив автобан! Врятуй механіків, заведи конвой — і брама встоїть.'),
    },
    objectives: [
      {
        id: 'deu-workshop',
        kind: 'rescue',
        icon: '🔧',
        site: 'workshop',
        title: () => t('Врятуй механіків із майстерні'),
        start: () => t('Механіки замкнулись у майстерні. Без них конвой не поїде!'),
        done: () => t('Механіки вільні! Тепер заведи вантажівки на автобані.'),
        reward: 110,
        horde: 12,
      },
      {
        id: 'deu-convoy',
        kind: 'activate',
        icon: '🚚',
        site: 'autobahn',
        title: () => t('Заведи 3 вантажівки конвою'),
        prompt: () => t('Тримай E — заведи вантажівку'),
        start: () => t('Конвой із припасами застряг. Заведи вантажівки, поки зомбі не рознесли вантаж!'),
        done: () => t('Конвой рушив! Лишилося відбити міську браму.'),
        count: 3,
        hold: 1.2,
        reward: 130,
        horde: 14,
      },
      {
        id: 'deu-gate',
        kind: 'defense',
        icon: '🛡️',
        site: 'cityGate',
        title: () => t('Відбий штурм міської брами'),
        start: () => t('Барон послав орду на браму. Не пропусти нікого!'),
        done: () => t('Брама встояла! Але казарма продовжує випускати зомбі — зруйнуй її.'),
        reward: 150,
        horde: 0,
      },
      {
        id: 'deu-barracks',
        kind: 'barracks',
        icon: '🏚️',
        site: 'barracks',
        title: () => t('Зламай казарму зомбі'),
        start: () => t('Казарма безупинно випускає зомбі. Зруйнуй її, поки їх не стало надто багато!'),
        done: () => t('Казарму зруйновано. Підкріплення не прийде — тепер зустрінь Барона на арені!'),
        reward: 220,
        horde: 0,
      },
    ],
  },
  FRA: {
    id: 'FRA',
    title: () => t('Куля над Парижем'),
    npc: {
      id: 'fra-pierre',
      kind: 'kid',
      site: 'cafe',
      name: () => t('Пекарчук П\'єр'),
      intro: () => t('Шеф Багет зачаклував місто! Врятуй кухарів, запусти повітряну кулю й зачисть зомбі-бази.'),
    },
    objectives: [
      {
        id: 'fra-kitchen',
        kind: 'rescue',
        icon: '🥐',
        site: 'bakery',
        title: () => t('Врятуй кухарів із пекарні'),
        start: () => t('Кухарі сховалися серед мішків із борошном. Виведи їх!'),
        done: () => t('Кухарі вільні! Тепер заправ повітряну кулю.'),
        reward: 120,
        horde: 12,
      },
      {
        id: 'fra-balloon',
        kind: 'fetch',
        icon: '🎈',
        site: 'balloonField',
        title: () => t('Заправ повітряну кулю'),
        prompt: () => t('Натисни E — візьми балон газу'),
        deliverPrompt: () => t('Тримай E — заправ кулю'),
        start: () => t('Куля полетить по допомогу, щойно знайдеш балони з газом.'),
        done: () => t('Куля в небі! Лишився винний склад.'),
        count: 3,
        hold: 2,
        reward: 140,
        horde: 14,
      },
      {
        id: 'fra-cellar',
        kind: 'survive',
        icon: '🍇',
        site: 'wineCellar',
        title: () => t('Зачисть виноградний склад'),
        start: () => t('Зомбі залізли у склад із виноградом. Вижени їх — урожай не для них!'),
        done: () => t('Склад чистий! Тепер знищ три зомбі-бази.'),
        count: 8,
        reward: 160,
        horde: 0,
      },
      {
        id: 'fra-bases',
        kind: 'bases',
        icon: '🏚️',
        site: 'wineCellar',
        title: () => t('Зачисть 3 зомбі-бази'),
        start: () => t('Три зомбі-бази оточили Париж. Знищ їх разом з охороною.'),
        done: () => t('Усі бази знищено! Шеф Багет чекає на арені.'),
        reward: 180,
        horde: 0,
      },
    ],
  },
  ESP: {
    id: 'ESP',
    title: () => t('Фієста повертається'),
    npc: {
      id: 'esp-carmen',
      kind: 'granny',
      site: 'fiestaSquare',
      name: () => t('Сеньйора Кармен'),
      intro: () => t('Матадор-Зомбі розігнав фієсту! Врятуй музикантів, вдар у дзвін — і свято повернеться.'),
    },
    objectives: [
      {
        id: 'esp-band',
        kind: 'rescue',
        icon: '🎺',
        site: 'musicians',
        title: () => t('Врятуй музикантів фієсти'),
        start: () => t('Оркестр сховався від Матадора. Без труб фієста мовчить!'),
        done: () => t('Музиканти врятовані! Тепер удар у святковий дзвін.'),
        reward: 120,
        horde: 12,
      },
      {
        id: 'esp-bells',
        kind: 'hold',
        icon: '🔔',
        site: 'bellTower',
        title: () => t('Вдар у дзвін на вежі'),
        prompt: () => t('Тримай E — дзвони!'),
        start: () => t('Дзвін на вежі скликає все місто. Хай лунає!'),
        done: () => t('Дзвін лунає над містом! Лишився склад феєрверків.'),
        hold: 2.4,
        reward: 140,
        horde: 14,
      },
      {
        id: 'esp-fireworks',
        kind: 'survive',
        icon: '🎆',
        site: 'fireworks',
        title: () => t('Відбий склад феєрверків'),
        start: () => t('Зомбі лізуть до феєрверків! Без салюту фієста не фієста.'),
        done: () => t('Феєрверки цілі! Матадор жде на арені — оле!'),
        count: 8,
        reward: 160,
        horde: 0,
      },
    ],
  },
  PRT: {
    id: 'PRT',
    title: () => t('Маяк Атлантики'),
    npc: {
      id: 'prt-joao',
      kind: 'kid',
      site: 'harborSquare',
      name: () => t('Юнга Жоан'),
      intro: () => t('Капітан Атлантик загасив маяк, і кораблі не бачать берега! Врятуй рибалок і поверни світло.'),
    },
    objectives: [
      {
        id: 'prt-fishers',
        kind: 'rescue',
        icon: '⛵',
        site: 'netShed',
        title: () => t('Виведи рибалок у безпеку'),
        start: () => t('Рибалки заплуталися у власних сітях зі страху. Виведи їх!'),
        done: () => t('Рибалки на березі! Тепер запали маяк.'),
        reward: 130,
        horde: 12,
      },
      {
        id: 'prt-lighthouse',
        kind: 'hold',
        icon: '🚨',
        site: 'lighthouse',
        title: () => t('Запали маяк Атлантики'),
        prompt: () => t('Тримай E — запали вогонь маяка'),
        start: () => t('Без маяка кораблі з допомогою не знайдуть порт.'),
        done: () => t('Маяк світить! Лишився портовий склад.'),
        hold: 2.6,
        reward: 150,
        horde: 14,
      },
      {
        id: 'prt-docks',
        kind: 'survive',
        icon: '⚓',
        site: 'docks',
        title: () => t('Зачисть портовий склад'),
        start: () => t('Зомбі окупували склад у порту. Вибий їх до прибуття кораблів!'),
        done: () => t('Порт вільний! Капітан Атлантик виходить на арену.'),
        count: 8,
        reward: 170,
        horde: 0,
      },
    ],
  },
  ITA: {
    id: 'ITA',
    title: () => t('Фонтан бажань'),
    npc: {
      id: 'ita-lucia',
      kind: 'granny',
      site: 'fountainSquare',
      name: () => t('Нонна Лючія'),
      intro: () => t('Цезар-Зомбі розбудив свій легіон! Врятуй кухарів, полагодь акведук — і Рим оживе.'),
    },
    objectives: [
      {
        id: 'ita-trattoria',
        kind: 'rescue',
        icon: '🍕',
        site: 'trattoria',
        title: () => t('Врятуй кухарів тратторії'),
        start: () => t('Кухарі забарикадувалися піцами. Смачно, але не надійно — виведи їх!'),
        done: () => t('Кухарі врятовані! Тепер полагодь старий акведук.'),
        reward: 130,
        horde: 12,
      },
      {
        id: 'ita-aqueduct',
        kind: 'hold',
        icon: '⛲',
        site: 'aqueduct',
        title: () => t('Полагодь старий акведук'),
        prompt: () => t('Тримай E — відкрути вентиль'),
        start: () => t('Без води фонтан бажань мовчить, а місту потрібні бажання!'),
        done: () => t('Вода тече, фонтан співає! Лишився табір легіону.'),
        hold: 2.6,
        reward: 150,
        horde: 14,
      },
      {
        id: 'ita-legion',
        kind: 'survive',
        icon: '🏛️',
        site: 'legionCamp',
        title: () => t('Розбий табір легіону'),
        start: () => t('Теракотовий легіон Цезаря став табором біля складу. Розжени їх!'),
        done: () => t('Легіон розбитий! Цезар чекає тебе в Колізеї.'),
        count: 8,
        reward: 170,
        horde: 0,
      },
    ],
  },
  TUR: {
    id: 'TUR',
    title: () => t('Килими й Босфор'),
    npc: {
      id: 'tur-ayse',
      kind: 'granny',
      site: 'teaGarden',
      name: () => t('Тітонька Айше'),
      intro: () => t('Паша Кебаб розкидав килими Великого базару! Поверни їх, засвіти маяк і підготуй рятувальний корабель.'),
    },
    objectives: [
      {
        id: 'tur-bazaar',
        kind: 'fetch',
        icon: '🧿',
        site: 'grandBazaar',
        title: () => t('Поверни килими на Великий базар'),
        prompt: () => t('Натисни E — підбери килим'),
        deliverPrompt: () => t('Тримай E — розклади килими'),
        start: () => t('Без килимів базар сумує. Знайди їх і поверни на місце!'),
        done: () => t('Базар знову сяє! Тепер засвіти маяк Босфору.'),
        count: 3,
        hold: 2,
        reward: 140,
        horde: 12,
      },
      {
        id: 'tur-lighthouse',
        kind: 'hold',
        icon: '🗼',
        site: 'bosphorusTower',
        title: () => t('Засвіти маяк Босфору'),
        prompt: () => t('Тримай E — засвіти маяк'),
        start: () => t('Маяк Босфору погас — кораблі кружляють у темряві.'),
        done: () => t('Маяк світить через протоку! Лишився склад спецій.'),
        hold: 2.6,
        reward: 160,
        horde: 14,
      },
      {
        id: 'tur-spices',
        kind: 'survive',
        icon: '🌶️',
        site: 'spiceDepot',
        title: () => t('Відбий склад спецій'),
        start: () => t('Зомбі чхають, але лізуть до спецій. Прожени їх!'),
        done: () => t('Спеції врятовано! Тепер відремонтуй корабель і забери людей з берега.'),
        count: 8,
        reward: 180,
        horde: 0,
      },
      {
        id: 'tur-rescue-ship',
        kind: 'shiprescue',
        icon: '🚢',
        site: 'shipDock',
        title: () => t('Відремонтуй корабель і врятуй людей'),
        start: () => t('Знайди ящик із дошками, полагодь корабель і переправ людей на безпечний берег.'),
        done: () => t('Людей висаджено на сушу! Паша Кебаб чекає на арені.'),
        reward: 260,
        horde: 0,
      },
    ],
  },
  SWE: {
    id: 'SWE',
    title: () => t('Північне сяйво'),
    npc: {
      id: 'swe-erik',
      kind: 'kid',
      site: 'townSquare',
      name: () => t('Малий вікінг Ерік'),
      intro: () => t('Сніговий Ярл украв північне сяйво! Врятуй людей із довгого дому і поверни небу світло.'),
    },
    objectives: [
      {
        id: 'swe-longhouse',
        kind: 'rescue',
        icon: '🛶',
        site: 'longhouse',
        title: () => t('Виведи людей із довгого дому'),
        start: () => t('Люди гріються в довгому домі, а надворі сніговики-зомбі. Виведи всіх!'),
        done: () => t('Люди в теплі й безпеці! Тепер поверни сяйво.'),
        reward: 140,
        horde: 12,
      },
      {
        id: 'swe-aurora',
        kind: 'hold',
        icon: '🌌',
        site: 'auroraTower',
        title: () => t('Полагодь вежу північного сяйва'),
        prompt: () => t('Тримай E — запусти сяйво'),
        start: () => t('Без вежі небо сіре, як каша. Поверни північне сяйво!'),
        done: () => t('Небо танцює зеленим! Лишився табір Ярла.'),
        hold: 2.6,
        reward: 160,
        horde: 14,
      },
      {
        id: 'swe-jarl',
        kind: 'survive',
        icon: '❄️',
        site: 'jarlCamp',
        title: () => t('Розжени табір Ярла'),
        start: () => t('Сніговики Ярла зібралися біля депо. Покажи їм, де зима закінчується!'),
        done: () => t('Табір розбитий! Сніговий Ярл жде на арені.'),
        count: 8,
        reward: 180,
        horde: 0,
      },
    ],
  },
  EGY: {
    id: 'EGY',
    title: () => t('Таємниця піраміди'),
    npc: {
      id: 'egy-guide',
      kind: 'kid',
      site: 'oasis',
      name: () => t('Юний археолог'),
      intro: () => t('Печатки гробниці зламані. Знайди їх біля сфінкса й піраміди, поки фараон не прокинувся.'),
    },
    objectives: [
      {
        id: 'egy-seals',
        kind: 'fetch',
        icon: '🪬',
        site: 'seals',
        deliverSite: 'tombDoor',
        title: () => t('Знайди 2 печатки гробниці'),
        prompt: () => t('Натисни E — взяти печатку'),
        deliverPrompt: () => t('Тримай E — встав печатки у двері'),
        start: () => t('Перша печатка біля сфінкса, друга на шляху до піраміди.'),
        done: () => t('Двері відкрились. Мумії вже поруч!'),
        count: 2,
        hold: 2.4,
        reward: 140,
        horde: 12,
      },
      {
        id: 'egy-ambush',
        kind: 'survive',
        icon: '⚱️',
        site: 'tombDoor',
        title: () => t('Переживи напад мумій'),
        start: () => t('Гробниця прокинулась. Не дай муміям вийти назовні.'),
        done: () => t('Прокляття ослабло. Фараон вийде на бій.'),
        count: 10,
        reward: 160,
        horde: 0,
        zombieTypes: ['mummy', 'walker', 'runner'],
      },
    ],
  },
  JPN: {
    id: 'JPN',
    title: () => t('Сад тисячі ліхтариків'),
    npc: {
      id: 'jpn-yuki',
      kind: 'kid',
      site: 'toriiGate',
      name: () => t('Учениця ніндзя Юкі'),
      intro: () => t('Сумо-Зомбі потоптав сад ліхтариків! Врятуй садівників і поверни світло святу.'),
    },
    objectives: [
      {
        id: 'jpn-teahouse',
        kind: 'rescue',
        icon: '🌸',
        site: 'teaHouse',
        title: () => t('Врятуй садівників із чайного дому'),
        start: () => t('Садівники сховалися за ширмами чайного дому. Виведи їх тихо, як ніндзя!'),
        done: () => t('Садівники врятовані! Тепер засвіти ліхтарі.'),
        reward: 150,
        horde: 12,
      },
      {
        id: 'jpn-lanterns',
        kind: 'hold',
        icon: '🏮',
        site: 'lanternHill',
        title: () => t('Засвіти ліхтарі на пагорбі'),
        prompt: () => t('Тримай E — засвіти гірлянду'),
        start: () => t('Гірлянда ліхтариків обірвана. Без світла свято не почнеться!'),
        done: () => t('Ліхтарики сяють! Лишилося додзьо.'),
        hold: 2.6,
        reward: 170,
        horde: 14,
      },
      {
        id: 'jpn-dojo',
        kind: 'survive',
        icon: '🥋',
        site: 'dojo',
        title: () => t('Зачисть додзьо від зомбі'),
        start: () => t('Зомбі влаштували в додзьо свій турнір. Покажи їм справжню техніку!'),
        done: () => t('Додзьо вільне! Сумо-Зомбі викликає тебе на арену.'),
        count: 8,
        reward: 190,
        horde: 0,
      },
    ],
  },
  CHN: {
    id: 'CHN',
    title: () => t('Вогні Великої стіни'),
    npc: {
      id: 'chn-mei',
      kind: 'granny',
      site: 'teaMarket',
      name: () => t('Майстриня Мей'),
      intro: () => t('Теракотовий Імператор підняв глиняне військо! Запали сигнальну вежу — і фортеця прокинеться.'),
    },
    objectives: [
      {
        id: 'chn-scrolls',
        kind: 'rescue',
        icon: '📜',
        site: 'scrollHouse',
        title: () => t('Врятуй учених із дому сувоїв'),
        start: () => t('Учені бережуть стародавні сувої і бояться вийти. Проведи їх!'),
        done: () => t('Учені та сувої в безпеці! Тепер запали сигнальну вежу.'),
        reward: 150,
        horde: 12,
      },
      {
        id: 'chn-beacon',
        kind: 'hold',
        icon: '🔥',
        site: 'beaconTower',
        title: () => t('Запали сигнальну вежу'),
        prompt: () => t('Тримай E — запали сигнальний вогонь'),
        start: () => t('Сигнальний вогонь стіни скликає захисників з усього краю.'),
        done: () => t('Вогонь палає над стіною! Лишився теракотовий розкоп.'),
        hold: 2.6,
        reward: 170,
        horde: 14,
      },
      {
        id: 'chn-pit',
        kind: 'survive',
        icon: '🏺',
        site: 'terracottaPit',
        title: () => t('Зачисть теракотовий розкоп'),
        start: () => t('Глиняні воїни лізуть із розкопу, як гриби після дощу. Зупини їх!'),
        done: () => t('Розкоп затих! Імператор сам виходить на арену.'),
        count: 8,
        reward: 190,
        horde: 0,
      },
    ],
  },
};

export function getCountryStory(countryId) {
  return STORIES[countryId] || null;
}

export function storyPreview(countryId) {
  const story = getCountryStory(countryId);
  return story ? story.objectives.map((o) => o.icon) : null;
}

export function shouldUseStoryMissions({ countryId, modeId, isGuest, isCoop, isPlayground }) {
  return modeId === 'campaign'
    && !isGuest
    && !isCoop
    && !isPlayground
    && !!getCountryStory(countryId);
}
